Implement binary format for test outputs and errors
tsoding/porth pull request #52
Opened 2021-09-26 20:47 UTC by kolumb

Tried to implement binary format that was described in #50

2021-09-26 21:43 UTC, drocha87 commented
@kolumb since you are working on the tests I would like to point something. There are some tests which have a long output (like `stack.porth` for example), and then is a little bit hard to spot where the error is (imagine a more complex output).

I don't know if is possible or simple to implement a way to tell where the output has diverged, something like running a `diff` (if the user has it installed) and then printing the result to output, or something like this. 

Maybe one way to solve this is breaking the tests in small pieces and have more detailed tests somehow.

2021-09-26 21:46 UTC, drocha87 commented
And I think the `test.py` should have a flag to stop the tests as soon as it fails or maybe a flag to run the tests silently and only output the broken tests, what you think?

2021-09-26 22:01 UTC, kolumb commented
I think that it could be reported as separate issue that this PR introduces.
Because, if I understand correctly, right now main priority that author has is to rewrite compiler and test script in porth. So I tried to keep everything as simple as possible. I contributed only because I thought that this PR could be helpful for rewriting process.

2021-09-27 08:34 UTC, rexim requested changes

2021-09-27 08:34 UTC, rexim commented on README.md
> +Test cases are located in [./tests/](./tests/) folder. The `*.bin` files are the expected outputs of the corresponding programs in binary format (1 byte - return code, 8 bytes - length of output, out
Please present the format as it was described originally inside of a code block:
```
|1 byte -- expected return code|
|8 bytes -- length of stdout|
|len(stdout) bytes -- the expected stdout encoded as UTF-8|
|8 bytes -- length of stderr|
|len(stderr) bytes -- the expected stderr encoded as UTF-8|
```

2021-09-27 08:34 UTC, rexim commented on test.py
> +                index = 0
The `read` method has an optional `size` in bytes. You can read the chunks of corresponding size without maintaining this `index`.

2021-09-27 08:34 UTC, rexim commented on test.py
> +                bin_file.write(
Split this into several writes. No need to concatenate anything.

2021-09-27 08:45 UTC, rexim commented
The fact that binary files are not displayed properly in diffs is definitely an issue. I'll need to think about a better simple format.

2021-09-27 09:35 UTC, rexim commented
Something like this. What do you guys think?

2021-09-27 09:48 UTC, rexim approved these changes

2021-09-27 09:52 UTC, rexim commented
@kolumb thank you for the contribution! :+1:

2021-09-27 09:52 UTC, merged